apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::385105852446:user/swarajbabu
      username: swarajbabu
      groups:
        - system:masters
