apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: 299139630689.dkr.ecr.ap-south-1.amazonaws.com/expense-backend:latest

        ports:
        - containerPort: 8000