apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: 299139630689.dkr.ecr.ap-south-1.amazonaws.com/expense-frontend:latest

        ports:
        - containerPort: 80